[server]
port = 8501
headless = false

[global]
disableWatchdogWarning = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF4B4B" # A bright contrast shade for primary buttons
backgroundColor = "#FFFFFF" # White background
secondaryBackgroundColor = "#F0F2F6" # Light grey for secondary elements
textColor = "#303030" # Dark grey for text
font = "sans serif"